### ISSUE TITLE
Checklist de Organizacion del evento

### ISSUE THREAD

**Issue by eafelix** [banode/organizadores#9]
Aqui va definida la lista para no perder ningún punto en la organización de los eventos. 
Puntos que surgen de nuestra propia experiencia, recomendaciones de otras comunidades, etc.
Obviamente todos somos libres de ir discutiendo y corrigiendo cosas.
- [ ]  Confirmar hosts.
- [ ]  Confirmar sponsors. 
- [ ]  Confirmar Charlas ( 2 charlas de 20 a 30 minutos cada uno con espacio a lighting talk).
- [ ]  Confirmar Fecha y Hora antes de promocionar el evento.
- [ ]  Actualizar Web con los datos de sponsors , fechas. 
- [ ]  Actualizar Meetup y abrir la inscripción. 
- [ ]  Generar Formulario de confirmación (Revisar este punto en issue )
- [ ]  Ver extras como stickers , snacks , etc.  
- [ ]  Generar encuesta post evento.

Checklist de items necesarios para el hosting : 
El host del evento debe tener estas características para que la experiencia sea optima y agradable.
- [ ] Equipo de presentación 
- [ ] Disponibilidad de espacio de trabajo compartido para promover la camaradería 
- [ ] Conexiones a red disponibles para todos los invitados
- [ ] Acceso a toma corrientes para las notebooks de los participantes

Checklist de items necesarios para la difusión: 
- [ ] Armado de Material para Redes sociales y Email para difusión.
- [ ] Notificaciones en Twitter periódicas a partir del lanzamiento.
- [ ] Notificaciones en Facebook periódicas a partir del lanzamiento.
- [ ] Notificaciones en Listas de Mail a partir del lanzamiento.

**Comment by andreslozadamosto** [comment]
Buenas, yo estoy viendo el tema de stickers para el meetup de php que tb estoy ayudando a organizar... averigue por ML y tardan 5/7 dias en promedio y se pueden pedir cualquier cantidad de planchas y cada plancha puede tener un diseño diferente. Si quieren luego les paso la data que averigue y talvez si llego a pedir para los dos meetup nos hagan precio por cantidad... 

Para el tema de difusion se puede utilizar una herramienta tipo tiempy.com Es de un emprendedor argentino, talvez si le tiramos la onda nos puede dar una mano. 

Saludos!

**Comment by eafelix** [comment]
Genial, con @a0viedo venimos laburando con https://www.stickermule.com/. 
Que onda la calidad? 

Por otro lado, genial lo de tiempy.com, pinta ser una buena herramienta.
Vos te encargas de chequear que tal esta para usar?

**Comment by andreslozadamosto** [comment]
Dale, yo reviso Tiempy y luego les cuento.

La calidad de las etiquetas ni idea... pero en estos dias voy a estar definiendo eso asi que tb les cuento. Pongo como fecha limite el viernes por el tiempo q tardan.

En esa pagina las envian a Arg? o solo es para bajar los diseños y luego los mandas a hacer aca?

**Comment by andreslozadamosto** [comment]
Buenas!
Como vienen con el tema del lugar y fecha? Les cuento que estuve averiguando y las oficinas de MUG (microsoft user group) cierran 8.30 q a mi parecer es muy temprano (no se si abren los sabados) y las oficinas de Kleer no tienen problemas pero estan en remodelaciones y por ahora no pueden hostear meetups.
Por otro lado, tengo el contacto de la gente de Wayra que es donde organice el meetup de php anterior. El lugar esta bueno, sobre todo la terraza. El unico problema es el tema de proyectar cosas que el proyector es en el lugar donde todos los equipos laburan (Es un espacio totalmente abierto). Si quieren puedo averiguar para ir a verlo...

**Comment by eafelix** [comment]
Perdon @alfathenus por no contestarte el issue. vos estas ya al tanto de todo para el miercoles verdad?

**Comment by andreslozadamosto** [comment]
@eafelix supongo q si... el miercoles en Waira... alguna novedad mas? perdon estos ultimos dias no estuve al tanto de lo que estuvieron hablando... Falta ayudar en algo mas para la organizacion?
